/**
 * ════════════════════════════════════════
 *  SIVA GOLD & SILVER — Product Data File
 * ════════════════════════════════════════
 *
 *  ONE LIST — WORKS FOR BOTH COLLECTIONS & GALLERY
 *
 *  Just add your items once in the  items: [ ]  array below.
 *
 *  gallery:true   → image also shows in the Gallery section
 *  featured:true  → image shows on HOMEPAGE gallery (first 6 used)
 *
 *  HOW TO ADD:
 *  { id:"c15", no:"200", img:"assets/collections/Dollar/200.webp",
 *    name:"Murugan Pendant", sub:"22K Yellow Gold", weight:"3.000 G",
 *    badge:"", category:"pendants", gallery:true, featured:false }
 *
 *  badge    = "New" | "Popular" | "Rare" | ""
 *  category = "rings"|"necklaces"|"bangles"|"earrings"|"pendants"|"bridal"|"silver"
 * ════════════════════════════════════════
 */

const SIVA_DATA = {

  items: [
    { id:"c1",  no:"001", img:"assets/collections/Dollar/001.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"New",     category:"pendants", gallery:true, featured:true  },
    { id:"c2",  no:"002", img:"assets/collections/Dollar/002.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"3.500 G",  badge:"",        category:"pendants", gallery:true, featured:true  },
    { id:"c3",  no:"285", img:"assets/collections/Dollar/285.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"4.000 G",  badge:"Popular", category:"pendants", gallery:true, featured:true  },
    { id:"c4",  no:"234", img:"assets/collections/Dollar/234.webp", name:"Krishna Pendant",     sub:"22K Yellow Gold", weight:"3.000 G",  badge:"",        category:"pendants", gallery:true, featured:true  },
    { id:"c5",  no:"167", img:"assets/collections/Dollar/167.webp", name:"Thirupathi Pendant",  sub:"22K Yellow Gold", weight:"3.000 G",  badge:"",        category:"pendants", gallery:true, featured:true  },
    { id:"c6",  no:"189", img:"assets/collections/Dollar/189.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"3.000 G",  badge:"",        category:"pendants", gallery:true, featured:true  },
    { id:"c7",  no:"226", img:"assets/collections/Dollar/226.webp", name:"Murugan Pendant",     sub:"22K Yellow Gold", weight:"4.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c8",  no:"141", img:"assets/collections/Dollar/141.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"1.200 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c9",  no:"013", img:"assets/collections/Dollar/013.webp", name:"Sivan Pendant",       sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c10", no:"137", img:"assets/collections/Dollar/137.webp", name:"Saibaba Pendant",     sub:"22K Yellow Gold", weight:"2.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c11", no:"130", img:"assets/collections/Dollar/130.webp", name:"Lakshmi Pendant",     sub:"22K Yellow Gold", weight:"4.000 G",  badge:"New",     category:"pendants", gallery:true, featured:false },
    { id:"c12", no:"123", img:"assets/collections/Dollar/123.webp", name:"Thirupathi Pendant",  sub:"22K Yellow Gold", weight:"10.000 G", badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c13", no:"131", img:"assets/collections/Dollar/131.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"3.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c14", no:"190", img:"assets/collections/Dollar/190.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c15", no:"183", img:"assets/collections/Dollar/183.webp", name:"Vishnu Pendant",     sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c16", no:"172", img:"assets/collections/Dollar/172.webp", name:"Murugan Pendant",     sub:"22K Yellow Gold", weight:"1.200 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c17", no:"244", img:"assets/collections/Dollar/244.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"3.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c18", no:"076", img:"assets/collections/Dollar/076.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c19", no:"180", img:"assets/collections/Dollar/180.webp", name:"Om Pendant",      sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c20", no:"176", img:"assets/collections/Dollar/176.webp", name:"Saraswathi Pendant",      sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c21", no:"227", img:"assets/collections/Dollar/227.webp", name:"Anchor Pendant",      sub:"22K Yellow Gold", weight:"4.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c22", no:"174", img:"assets/collections/Dollar/174.webp", name:"Murugan Pendant",      sub:"22K Yellow Gold", weight:"3.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c23", no:"011", img:"assets/collections/Dollar/011.webp", name:"Krishna Pendant",      sub:"22K Yellow Gold", weight:"8.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c24", no:"135", img:"assets/collections/Dollar/135.webp", name:"Thirupathi Pendant",      sub:"22K Yellow Gold", weight:"2.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c25", no:"284", img:"assets/collections/Dollar/284.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c26", no:"014", img:"assets/collections/Dollar/014.webp", name:"Om Pendant",      sub:"22K Yellow Gold", weight:"2.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c27", no:"140", img:"assets/collections/Dollar/140.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"1.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c28", no:"165", img:"assets/collections/Dollar/165.webp", name:"Thirupathi Pendant",      sub:"22K Yellow Gold", weight:"6.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c29", no:"134", img:"assets/collections/Dollar/134.webp", name:"Krishna Pendant",      sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c30", no:"133", img:"assets/collections/Dollar/133.webp", name:"Murugan Pendant",      sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c31", no:"188", img:"assets/collections/Dollar/188.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c32", no:"267", img:"assets/collections/Dollar/267.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"1.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c33", no:"006", img:"assets/collections/Dollar/006.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c34", no:"185", img:"assets/collections/Dollar/185.webp", name:"Swastika Pendant",      sub:"22K Yellow Gold", weight:"2.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c35", no:"175", img:"assets/collections/Dollar/175.webp", name:"Lakshmi Pendant",      sub:"22K Yellow Gold", weight:"3.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c36", no:"120", img:"assets/collections/Dollar/120.webp", name:"Siluvai Pendant",      sub:"22K Yellow Gold", weight:"7.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c37", no:"108", img:"assets/collections/Dollar/108.webp", name:"Siluvai Pendant",      sub:"22K Yellow Gold", weight:"3.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c38", no:"107", img:"assets/collections/Dollar/107.webp", name:"Siluvai Pendant",      sub:"22K Yellow Gold", weight:"2.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c39", no:"265", img:"assets/collections/Dollar/265.webp", name:"Anthonyar Pendant",      sub:"22K Yellow Gold", weight:"8.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c40", no:"071", img:"assets/collections/Dollar/071.webp", name:"Heart Pendant",      sub:"22K Yellow Gold", weight:"2.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c41", no:"213", img:"assets/collections/Dollar/213.webp", name:"Siluvai Pendant",      sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c42", no:"077", img:"assets/collections/Dollar/077.webp", name:"Heart Pendant",      sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c43", no:"143", img:"assets/collections/Dollar/143.webp", name:"Eagle Pendant",      sub:"22K Yellow Gold", weight:"1.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c44", no:"053", img:"assets/collections/Dollar/053.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c45", no:"058", img:"assets/collections/Dollar/058.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"1.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c46", no:"269", img:"assets/collections/Dollar/269.webp", name:"Fish Pendant",      sub:"22K Yellow Gold", weight:"3.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c47", no:"031", img:"assets/collections/Dollar/031.webp", name:"Fish Pendant",      sub:"22K Yellow Gold", weight:"0.800 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c48", no:"271", img:"assets/collections/Dollar/271.webp", name:"Lion Pendant",      sub:"22K Yellow Gold", weight:"4.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c49", no:"043", img:"assets/collections/Dollar/043.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"2.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c50", no:"072", img:"assets/collections/Dollar/072.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c51", no:"209", img:"assets/collections/Dollar/209.webp", name:"Elephant Pendant",      sub:"22K Yellow Gold", weight:"2.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c52", no:"145", img:"assets/collections/Dollar/145.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"2.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c53", no:"229", img:"assets/collections/Dollar/229.webp", name:"Letter Pendant",      sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c54", no:"022", img:"assets/collections/Dollar/022.webp", name:"Horse Pendant",      sub:"22K Yellow Gold", weight:"2.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c55", no:"235", img:"assets/collections/Dollar/235.webp", name:"Fish Pendant",      sub:"22K Yellow Gold", weight:"4.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c56", no:"228", img:"assets/collections/Dollar/228.webp", name:"Heart Pendant",      sub:"22K Yellow Gold", weight:"4.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c57", no:"236", img:"assets/collections/Dollar/236.webp", name:"Letter Pendant",      sub:"22K Yellow Gold", weight:"4.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c58", no:"247", img:"assets/collections/Dollar/247.webp", name:"Letter Pendant",      sub:"22K Yellow Gold", weight:"4.500 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c59", no:"248", img:"assets/collections/Dollar/248.webp", name:"Mother Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },

    /**
     * Dollar Collection without numbers (Do1.png, Do2.png, etc.) - 22K Yellow Gold Pendants
     */
    
    { id:"c60", no:"", img:"assets/collections/Dollar/Do1.webp", name:"Vel Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c61", no:"", img:"assets/collections/Dollar/Do2.webp", name:"Scorpion Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c62", no:"", img:"assets/collections/Dollar/Do3.webp", name:"Swastika Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c63", no:"", img:"assets/collections/Dollar/Do4.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c64", no:"", img:"assets/collections/Dollar/Do5.webp", name:"Siluvai Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c65", no:"", img:"assets/collections/Dollar/Do6.webp", name:"Lakshmi Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c67", no:"", img:"assets/collections/Dollar/Do8.webp", name:"Thirupathi Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c68", no:"", img:"assets/collections/Dollar/Do9.webp", name:"Swastika Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c69", no:"", img:"assets/collections/Dollar/Do10.webp", name:"Sivan Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c70", no:"", img:"assets/collections/Dollar/Do11.webp", name:"Raghavendra Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c71", no:"", img:"assets/collections/Dollar/Do12.webp", name:"Thirupathi Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c72", no:"", img:"assets/collections/Dollar/Do13.webp", name:"Vel Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c73", no:"", img:"assets/collections/Dollar/Do14.webp", name:"Lakshmi Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c74", no:"", img:"assets/collections/Dollar/Do15.webp", name:"Om Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c75", no:"", img:"assets/collections/Dollar/Do16.webp", name:"Gomathi Ammal Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c76", no:"", img:"assets/collections/Dollar/Do17.webp", name:"Vel Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c77", no:"", img:"assets/collections/Dollar/Do18.webp", name:"Thirupathi Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c78", no:"", img:"assets/collections/Dollar/Do19.webp", name:"Lakshmi Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c79", no:"", img:"assets/collections/Dollar/Do20.webp", name:"Vel Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c80", no:"", img:"assets/collections/Dollar/Do21.webp", name:"Sulautham Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c81", no:"", img:"assets/collections/Dollar/Do22.webp", name:"Om Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c82", no:"", img:"assets/collections/Dollar/Do23.webp", name:"Dental Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c83", no:"", img:"assets/collections/Dollar/Do24.webp", name:"Lakshmi Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c84", no:"", img:"assets/collections/Dollar/Do25.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c85", no:"", img:"assets/collections/Dollar/Do26.webp", name:"Letter Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c86", no:"", img:"assets/collections/Dollar/Do27.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c87", no:"", img:"assets/collections/Dollar/Do28.webp", name:"Siluvai Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c88", no:"", img:"assets/collections/Dollar/Do29.webp", name:"Heart Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c89", no:"", img:"assets/collections/Dollar/Do30.webp", name:"Heart Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c90", no:"", img:"assets/collections/Dollar/Do31.webp", name:"Thirupathi Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c91", no:"", img:"assets/collections/Dollar/Do32.webp", name:"Letter Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c92", no:"", img:"assets/collections/Dollar/Do33.webp", name:"Heart Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c93", no:"", img:"assets/collections/Dollar/Do34.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c94", no:"", img:"assets/collections/Dollar/Do35.webp", name:"Letter Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c95", no:"", img:"assets/collections/Dollar/Do36.webp", name:"Letter Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c96", no:"", img:"assets/collections/Dollar/Do37.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c97", no:"", img:"assets/collections/Dollar/Do38.webp", name:"Iyyappan Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c98", no:"", img:"assets/collections/Dollar/Do39.webp", name:"Mother Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c99", no:"", img:"assets/collections/Dollar/Do40.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c100", no:"", img:"assets/collections/Dollar/Do41.webp", name:"Lakshmi Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c101", no:"", img:"assets/collections/Dollar/Do42.webp", name:"Mother Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c102", no:"", img:"assets/collections/Dollar/Do43.webp", name:"Siluvai Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c103", no:"", img:"assets/collections/Dollar/Do44.webp", name:"Letter Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c104", no:"", img:"assets/collections/Dollar/Do45.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c105", no:"", img:"assets/collections/Dollar/Do46.webp", name:"Swastika Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c106", no:"", img:"assets/collections/Dollar/Do47.webp", name:"Heart Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c107", no:"", img:"assets/collections/Dollar/Do48.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c108", no:"", img:"assets/collections/Dollar/Do49.webp", name:"Mother Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c109", no:"", img:"assets/collections/Dollar/Do50.webp", name:"Letter Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c110", no:"", img:"assets/collections/Dollar/Do51.webp", name:"Om Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c111", no:"", img:"assets/collections/Dollar/Do52.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c112", no:"", img:"assets/collections/Dollar/Do53.webp", name:"Anjaneyar Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c113", no:"", img:"assets/collections/Dollar/Do54.webp", name:"Letter Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c114", no:"", img:"assets/collections/Dollar/Do55.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c115", no:"", img:"assets/collections/Dollar/Do56.webp", name:"Horse Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c116", no:"", img:"assets/collections/Dollar/Do57.webp", name:"Letter Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c117", no:"", img:"assets/collections/Dollar/Do58.webp", name:"Heart Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c118", no:"", img:"assets/collections/Dollar/Do59.webp", name:"Krishna Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c119", no:"", img:"assets/collections/Dollar/Do60.webp", name:"Thirupathi Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c120", no:"", img:"assets/collections/Dollar/Do61.webp", name:"Om Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c121", no:"", img:"assets/collections/Dollar/Do62.webp", name:"Elephant Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c122", no:"", img:"assets/collections/Dollar/Do63.webp", name:"Heart Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c123", no:"", img:"assets/collections/Dollar/Do64.webp", name:"Anchor Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c124", no:"", img:"assets/collections/Dollar/Do65.webp", name:"Heart Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c125", no:"", img:"assets/collections/Dollar/Do66.webp", name:"Murugan Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c126", no:"", img:"assets/collections/Dollar/Do67.webp", name:"Letter Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c127", no:"", img:"assets/collections/Dollar/Do68.webp", name:"Letter Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c128", no:"", img:"assets/collections/Dollar/Do69.webp", name:"Murugan Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c129", no:"", img:"assets/collections/Dollar/Do70.webp", name:"Thirupathi Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c130", no:"", img:"assets/collections/Dollar/Do71.webp", name:"Letter Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c131", no:"", img:"assets/collections/Dollar/Do72.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c132", no:"", img:"assets/collections/Dollar/Do73.webp", name:"Letter Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c133", no:"", img:"assets/collections/Dollar/Do74.webp", name:"Heart Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c134", no:"", img:"assets/collections/Dollar/Do75.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c135", no:"", img:"assets/collections/Dollar/Do76.webp", name:"Heart Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c136", no:"", img:"assets/collections/Dollar/Do77.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c137", no:"", img:"assets/collections/Dollar/Do78.webp", name:"Heart Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c138", no:"", img:"assets/collections/Dollar/Do79.webp", name:"Murugan Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c139", no:"", img:"assets/collections/Dollar/Do80.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c140", no:"", img:"assets/collections/Dollar/Do81.webp", name:"Sivan Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c141", no:"", img:"assets/collections/Dollar/Do82.webp", name:"Vel Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c142", no:"", img:"assets/collections/Dollar/Do83.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c143", no:"", img:"assets/collections/Dollar/Do84.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c144", no:"", img:"assets/collections/Dollar/Do85.webp", name:"Om Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c145", no:"", img:"assets/collections/Dollar/Do86.webp", name:"Letter Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c146", no:"", img:"assets/collections/Dollar/Do87.webp", name:"Vel Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c147", no:"", img:"assets/collections/Dollar/Do88.webp", name:"Vel Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c148", no:"", img:"assets/collections/Dollar/Do89.webp", name:"Vinayagar Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c149", no:"", img:"assets/collections/Dollar/Do90.webp", name:"Heart Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c150", no:"", img:"assets/collections/Dollar/Do91.webp", name:"Anchor Pendant",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"pendants", gallery:true, featured:false },

    /**
     * Double Dollar Collection without numbers (DD1.png, DD2.png, etc.) - 22K Yellow Gold Pendants
     */

    { id:"c151", no:"", img:"assets/collections/Double_dollar/DD1.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c152", no:"", img:"assets/collections/Double_dollar/DD2.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c153", no:"", img:"assets/collections/Double_dollar/DD3.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c154", no:"", img:"assets/collections/Double_dollar/DD4.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c155", no:"", img:"assets/collections/Double_dollar/DD5.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c156", no:"", img:"assets/collections/Double_dollar/DD6.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c157", no:"", img:"assets/collections/Double_dollar/DD7.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c158", no:"", img:"assets/collections/Double_dollar/DD8.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c159", no:"", img:"assets/collections/Double_dollar/DD9.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c160", no:"", img:"assets/collections/Double_dollar/DD10.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c161", no:"", img:"assets/collections/Double_dollar/DD11.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c162", no:"", img:"assets/collections/Double_dollar/DD12.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c163", no:"", img:"assets/collections/Double_dollar/DD13.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c164", no:"", img:"assets/collections/Double_dollar/DD14.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },
    { id:"c165", no:"", img:"assets/collections/Double_dollar/DD15.webp", name:"Design Pendant",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"pendants", gallery:true, featured:false },

    /**
     * Mens_Rings Collection with numbers (R1.png, R2.png, etc.) - 22K Yellow Gold Rings
     */

    { id:"c166", no:"1148", img:"assets/collections/Mens_Rings/1148.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"8.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c167", no:"192", img:"assets/collections/Mens_Rings/192.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"6.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c168", no:"206", img:"assets/collections/Mens_Rings/206.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"6.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c169", no:"a95", img:"assets/collections/Mens_Rings/a95.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"7.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c170", no:"a123", img:"assets/collections/Mens_Rings/a123.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"8.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c171", no:"025", img:"assets/collections/Mens_Rings/025.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"4.500 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c172", no:"022", img:"assets/collections/Mens_Rings/022.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"2.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c173", no:"1147", img:"assets/collections/Mens_Rings/1147.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"8.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c174", no:"005", img:"assets/collections/Mens_Rings/005.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"10.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c175", no:"017", img:"assets/collections/Mens_Rings/017.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"8.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c176", no:"137", img:"assets/collections/Mens_Rings/137.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"7.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c177", no:"248", img:"assets/collections/Mens_Rings/248.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"3.600 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c178", no:"a82", img:"assets/collections/Mens_Rings/a82.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"7.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c179", no:"063", img:"assets/collections/Mens_Rings/063.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"4.500 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c180", no:"060", img:"assets/collections/Mens_Rings/060.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"4.500 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c181", no:"209", img:"assets/collections/Mens_Rings/209.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"2.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c182", no:"073", img:"assets/collections/Mens_Rings/073.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"4.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c183", no:"100", img:"assets/collections/Mens_Rings/100.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"10.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c184", no:"1151", img:"assets/collections/Mens_Rings/1151.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"6.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c185", no:"a77", img:"assets/collections/Mens_Rings/a77.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"10.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c186", no:"039", img:"assets/collections/Mens_Rings/039.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"6.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c187", no:"", img:"assets/collections/Mens_Rings/0.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"4.500 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c188", no:"a79", img:"assets/collections/Mens_Rings/a79.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"8.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c189", no:"119", img:"assets/collections/Mens_Rings/119.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"4.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c190", no:"217", img:"assets/collections/Mens_Rings/217.webp", name:"Letter Ring",      sub:"22K Yellow Gold", weight:"6.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c191", no:"1124", img:"assets/collections/Mens_Rings/1124.webp", name:"Letter Ring",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c192", no:"219", img:"assets/collections/Mens_Rings/219.webp", name:"Letter Ring",      sub:"22K Yellow Gold", weight:"6.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c193", no:"230", img:"assets/collections/Mens_Rings/230.webp", name:"Letter Ring",      sub:"22K Yellow Gold", weight:"7.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c194", no:"145", img:"assets/collections/Mens_Rings/145.webp", name:"Letter Ring",      sub:"22K Yellow Gold", weight:"2.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c195", no:"a116", img:"assets/collections/Mens_Rings/a116.webp", name:"Letter Ring",      sub:"22K Yellow Gold", weight:"8.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c196", no:"a145", img:"assets/collections/Mens_Rings/a145.webp", name:"Letter Ring",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c197", no:"234", img:"assets/collections/Mens_Rings/234.webp", name:"Letter Ring",      sub:"22K Yellow Gold", weight:"9.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c198", no:"141", img:"assets/collections/Mens_Rings/141.webp", name:"Letter Ring",      sub:"22K Yellow Gold", weight:"6.500 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c199", no:"a117", img:"assets/collections/Mens_Rings/a117.webp", name:"Letter Ring",      sub:"22K Yellow Gold", weight:"7.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c200", no:"a115", img:"assets/collections/Mens_Rings/a115.webp", name:"Letter Ring",      sub:"22K Yellow Gold", weight:"8.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c201", no:"a92", img:"assets/collections/Mens_Rings/a92.webp", name:"Letter Ring",      sub:"22K Yellow Gold", weight:"6.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c202", no:"a10", img:"assets/collections/Mens_Rings/a10.webp", name:"Letter Ring",      sub:"22K Yellow Gold", weight:"12.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c203", no:"140", img:"assets/collections/Mens_Rings/140.webp", name:"Letter Ring",      sub:"22K Yellow Gold", weight:"6.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c204", no:"237", img:"assets/collections/Mens_Rings/237.webp", name:"Letter Ring",      sub:"22K Yellow Gold", weight:"12.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c205", no:"1165", img:"assets/collections/Mens_Rings/1165.webp", name:"Letter Ring",      sub:"22K Yellow Gold", weight:"4.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c206", no:"1154", img:"assets/collections/Mens_Rings/1154.webp", name:"Letter Ring",      sub:"22K Yellow Gold", weight:"4.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c207", no:"171", img:"assets/collections/Mens_Rings/171.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"6.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c208", no:"115", img:"assets/collections/Mens_Rings/115.webp", name:"Thirupathi Ring",      sub:"22K Yellow Gold", weight:"7.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c209", no:"a40", img:"assets/collections/Mens_Rings/a40.webp", name:"Thirupathi Ring",      sub:"22K Yellow Gold", weight:"4.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c210", no:"236", img:"assets/collections/Mens_Rings/236.webp", name:"Vinayagar Ring",      sub:"22K Yellow Gold", weight:"12.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c211", no:"", img:"assets/collections/Mens_Rings/00.webp", name:"Vinayagar Ring",      sub:"22K Yellow Gold", weight:"4.500 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c212", no:"238", img:"assets/collections/Mens_Rings/238.webp", name:"Thirupathi Ring",      sub:"22K Yellow Gold", weight:"10.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c213", no:"a15", img:"assets/collections/Mens_Rings/a15.webp", name:"Vinayagar Ring",      sub:"22K Yellow Gold", weight:"10.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c214", no:"1116", img:"assets/collections/Mens_Rings/1116.webp", name:"Vinayagar Ring",      sub:"22K Yellow Gold", weight:"12.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c215", no:"a1", img:"assets/collections/Mens_Rings/a1.webp", name:"Elephant Ring",      sub:"22K Yellow Gold", weight:"15.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c216", no:"129", img:"assets/collections/Mens_Rings/129.webp", name:"Vinayagar Ring",      sub:"22K Yellow Gold", weight:"7.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c217", no:"494", img:"assets/collections/Mens_Rings/494.webp", name:"Vinayagar Ring",      sub:"22K Yellow Gold", weight:"4.500 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c218", no:"a4", img:"assets/collections/Mens_Rings/a4.webp", name:"Lion Ring",      sub:"22K Yellow Gold", weight:"16.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c219", no:"a15", img:"assets/collections/Mens_Rings/a15 (2).webp", name:"Lakshmi Ring",      sub:"22K Yellow Gold", weight:"10.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c220", no:"", img:"assets/collections/Mens_Rings/132 (2).webp", name:"Vinayagar Ring",      sub:"22K Yellow Gold", weight:"8.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c221", no:"a45", img:"assets/collections/Mens_Rings/a45.webp", name:"Vinayagar Ring",      sub:"22K Yellow Gold", weight:"8.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c222", no:"1121", img:"assets/collections/Mens_Rings/1121.webp", name:"Thirupathi Ring",      sub:"22K Yellow Gold", weight:"8.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c223", no:"122", img:"assets/collections/Mens_Rings/122.webp", name:"Lion Ring",      sub:"22K Yellow Gold", weight:"10.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c224", no:"132", img:"assets/collections/Mens_Rings/132.webp", name:"Vinayagar Ring",      sub:"22K Yellow Gold", weight:"8.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
    { id:"c225", no:"a53", img:"assets/collections/Mens_Rings/a53.webp", name:"Lion Ring",      sub:"22K Yellow Gold", weight:"4.000 G",  badge:"",        category:"menrings", gallery:true, featured:false },
  
      /**
     * Ladies_Rings Collection with numbers (R1.png, R2.png, etc.) - 22K Yellow Gold Rings
     */
  
    { id:"c226", no:"1173", img:"assets/collections/Ladies_Rings/1173.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"1.500 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c227", no:"807", img:"assets/collections/Ladies_Rings/807.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"1.500 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c228", no:"1164", img:"assets/collections/Ladies_Rings/1164.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"2.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c229", no:"a131", img:"assets/collections/Ladies_Rings/a131.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"2.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c230", no:"720", img:"assets/collections/Ladies_Rings/720.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"2.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c231", no:"819", img:"assets/collections/Ladies_Rings/819.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"2.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c232", no:"767", img:"assets/collections/Ladies_Rings/767.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"2.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c233", no:"a132", img:"assets/collections/Ladies_Rings/a132.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"2.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c234", no:"433", img:"assets/collections/Ladies_Rings/433.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"2.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c235", no:"1113", img:"assets/collections/Ladies_Rings/1113.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c236", no:"797", img:"assets/collections/Ladies_Rings/797.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c237", no:"965", img:"assets/collections/Ladies_Rings/965.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c238", no:"315", img:"assets/collections/Ladies_Rings/315.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c239", no:"788", img:"assets/collections/Ladies_Rings/788.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c240", no:"a152", img:"assets/collections/Ladies_Rings/a152.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"2.500 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c241", no:"309", img:"assets/collections/Ladies_Rings/309.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"3.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c242", no:"953", img:"assets/collections/Ladies_Rings/953.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"3.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c243", no:"827", img:"assets/collections/Ladies_Rings/827.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"3.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c244", no:"358", img:"assets/collections/Ladies_Rings/358.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"3.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c245", no:"445", img:"assets/collections/Ladies_Rings/445.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"3.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c246", no:"443", img:"assets/collections/Ladies_Rings/443.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"3.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c247", no:"779", img:"assets/collections/Ladies_Rings/779.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"3.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c248", no:"441", img:"assets/collections/Ladies_Rings/441.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"3.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c249", no:"413", img:"assets/collections/Ladies_Rings/413.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"3.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c250", no:"1010", img:"assets/collections/Ladies_Rings/1010.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"3.500 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c251", no:"354", img:"assets/collections/Ladies_Rings/354.webp", name:"Om Ring",      sub:"22K Yellow Gold", weight:"3.500 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c252", no:"416", img:"assets/collections/Ladies_Rings/416.webp", name:"Vinayagar Ring",      sub:"22K Yellow Gold", weight:"3.500 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c253", no:"1140", img:"assets/collections/Ladies_Rings/1140.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"4.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c254", no:"1011", img:"assets/collections/Ladies_Rings/1011.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"4.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c255", no:"1060", img:"assets/collections/Ladies_Rings/1060.webp", name:"Om Ring",      sub:"22K Yellow Gold", weight:"4.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c256", no:"438", img:"assets/collections/Ladies_Rings/438.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"4.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c257", no:"328", img:"assets/collections/Ladies_Rings/328.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"4.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c258", no:"1134", img:"assets/collections/Ladies_Rings/1134.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"4.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c259", no:"1136", img:"assets/collections/Ladies_Rings/1136.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"4.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c260", no:"1135", img:"assets/collections/Ladies_Rings/1135.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"4.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c261", no:"412", img:"assets/collections/Ladies_Rings/412.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"4.500 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c262", no:"235", img:"assets/collections/Ladies_Rings/235.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"4.500 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c263", no:"a109", img:"assets/collections/Ladies_Rings/a109.webp", name:"Om Ring",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c264", no:"207", img:"assets/collections/Ladies_Rings/207.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c265", no:"109", img:"assets/collections/Ladies_Rings/109.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c266", no:"081", img:"assets/collections/Ladies_Rings/081.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c267", no:"a91", img:"assets/collections/Ladies_Rings/a91.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c268", no:"165", img:"assets/collections/Ladies_Rings/165.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c269", no:"175", img:"assets/collections/Ladies_Rings/175.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"5.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c270", no:"a136", img:"assets/collections/Ladies_Rings/a136.webp", name:"Vinayagar Ring",      sub:"22K Yellow Gold", weight:"5.500 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c271", no:"1155", img:"assets/collections/Ladies_Rings/1155.webp", name:"Design Ring",      sub:"22K Yellow Gold", weight:"6.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c272", no:"1122", img:"assets/collections/Ladies_Rings/1122.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"6.000 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    { id:"c273", no:"a112", img:"assets/collections/Ladies_Rings/a112.webp", name:"Stone Ring",      sub:"22K Yellow Gold", weight:"6.500 G",  badge:"",        category:"ladiesrings", gallery:true, featured:false },
    
    /**
     * Earrings Collection without numbers (DD1.png, DD2.png, etc.) - 22K Yellow Gold Pendants
     */

    { id:"c274", no:"D1", img:"assets/collections/Ear_Rings/D1.webp", name:"Design Earring",      sub:"22K Yellow Gold", weight:"7.000 G",  badge:"",        category:"earrings", gallery:true, featured:false },
    { id:"c275", no:"D2", img:"assets/collections/Ear_Rings/D2.webp", name:"Design Earring",      sub:"22K Yellow Gold", weight:"7.000 G",  badge:"",        category:"earrings", gallery:true, featured:false },
    { id:"c276", no:"D3", img:"assets/collections/Ear_Rings/D3.webp", name:"Design Earring",      sub:"22K Yellow Gold", weight:"7.000 G",  badge:"",        category:"earrings", gallery:true, featured:false },
    { id:"c277", no:"D4", img:"assets/collections/Ear_Rings/D4.webp", name:"Design Earring",      sub:"22K Yellow Gold", weight:"7.000 G",  badge:"",        category:"earrings", gallery:true, featured:false },
    { id:"c278", no:"D5", img:"assets/collections/Ear_Rings/D5.webp", name:"Design Earring",      sub:"22K Yellow Gold", weight:"7.000 G",  badge:"",        category:"earrings", gallery:true, featured:false },
    { id:"c279", no:"D6", img:"assets/collections/Ear_Rings/D6.webp", name:"Design Earring",      sub:"22K Yellow Gold", weight:"7.000 G",  badge:"",        category:"earrings", gallery:true, featured:false },
    { id:"c280", no:"D7", img:"assets/collections/Ear_Rings/D7.webp", name:"Design Earring",      sub:"22K Yellow Gold", weight:"7.000 G",  badge:"",        category:"earrings", gallery:true, featured:false },
    { id:"c281", no:"D8", img:"assets/collections/Ear_Rings/D8.webp", name:"Design Earring",      sub:"22K Yellow Gold", weight:"7.000 G",  badge:"",        category:"earrings", gallery:true, featured:false },


    /* ── ADD MORE BELOW ──
    { id:"c15", no:"200", img:"assets/collections/Dollar/200.webp", name:"", sub:"22K Yellow Gold", weight:"", badge:"", category:"pendants", gallery:true, featured:false },
    */
  ],

  /* ── derived automatically — do not edit ── */
  get collections() { return this.items; },
  get gallery()     { return this.items.filter(i => i.gallery); },

  /* Only list a category here once it actually has items —
     an empty category renders an empty grid. */
  categories: [
    { id:"all",          label:"All"         },
    { id:"pendants",     label:"Pendants"    },
    { id:"menrings",     label:"Men's Rings" },
    { id:"ladiesrings",  label:"Ladies Rings"},
    { id:"earrings",     label:"Earrings"    },
  ],
};
